name: Deploy Wavelet Website to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.147.9/hugo_extended_withdeploy_0.147.9_linux-amd64.tar.gz
          tar -xzf hugo_extended_withdeploy_0.147.9_linux-amd64.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      - name: Build Hugo site
        run: hugo --minify

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 and Invalidate CloudFront
        run: |
          # Hugo deploy handles both S3 upload and CloudFront invalidation
          echo "Deploying to S3 and invalidating CloudFront distribution E1SSLXGWCLEAZW"
          hugo deploy --target=production --maxDeletes -1 --invalidateCDN

      - name: Verify CloudFront Invalidation
        if: success()
        run: |
          echo "Checking recent CloudFront invalidations..."
          aws cloudfront list-invalidations \
            --distribution-id E1SSLXGWCLEAZW \
            --max-items 3 \
            --query 'InvalidationList.Items[0].[Id,Status,CreateTime]' \
            --output table
          echo "✅ Deployment and invalidation completed"

      - name: Verify deployment
        run: |
          echo "Site deployed to: https://www.wavelet.net"
          echo "Checking if site is accessible..."
          curl -I https://www.wavelet.net || true